name: nejsconf.com
description: The website of the NebraskaJS Conference
safe: false
baseurl: /
dist: "2.1.1"
markdown: rdiscount
permalink: /:year/:title/
highlighter: pygments
relative_permalinks: false
exclude:
 - node_modules
 - Gruntfile.js
 - sql
 - less
 - gulpfile.js
 - less
 - Gemfile
 - Gemfile.lock
 - README.md
 - package.json
 - src
 - deploy.sh
